### Recuperar todas las películas

GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Recuperar una películas por categoría
GET http://localhost:1234/movies?genre=Drama

### Crear una película

POST http://localhost:1234/movies
Content-Type: 'application/json'

{
    "title": "The Godfather",
    "year": 1972,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://www.imdb.com/title/tt0068646/mediaviewer/rm4263220224/",
    "genre": [
        "Crime",
        "Drama"
    ]
}

### Actualizar una película

PATCH http://localhost:1234/movies/0a697ec6-fe34-4a44-9133-03d55f0687cd
Content-Type: application/json

{
    "year": 1993
}